<a href="https://colab.research.google.com/github/l19060741/Curso-Phyton/blob/main/Anahi_Gonzalez_3_Reshaping_y_concatenaci%C3%B3n_de_arreglos_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reshaping arreglos Numpy

En ocasiones es necesario darle una forma distinta a los arreglos, para lo que se utiliza el método reshape().

In [ ]:
import numpy as np

In [ ]:
#Creamos un arreglo con 9 elementos
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#Verificamos la forma del arreglo
arr.shape

(9,)

In [ ]:
#Cambiamos la forma del arreglo usando la función reshape
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#La forma no cambia
arr.shape

(9,)

In [ ]:
#Lo asignamos a otra variable
malla = arr.reshape(3,3)

In [ ]:
# La forma si cambia
malla.shape

(3, 3)

In [ ]:
#Podemos hacerlo en un renglón
malla1=np.arange(1,10).reshape(3,3)

In [ ]:
#El arreglo original y con el cambio de forma deben tener el mismo tamaño, de lo contrario hay error
malla2=np.arange(1,10).reshape(3,4)

ValueError: ignored

In [ ]:
#Podemos pasar de un arreglo unidmensional a uno bidimensional
#Creamos un arreglo
x = np.array([1,2,3])

In [ ]:
#Verificamos su forma
x.shape

(3,)

In [ ]:
#Le damos una nueva forma
x.reshape(1,3)

array([[1, 2, 3]])

In [ ]:
#Verificamos la nueva forma
x.reshape(1,3).shape

(1, 3)

In [ ]:
#Le damos una nueva forma
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [ ]:
#Verificamos la nueva forma
x.reshape((3,1)).shape

(3, 1)

# Concatenación de arreglos

Es posible unir arreglos Numpy usando tres maneras distintas.

### np.concatenate

In [ ]:
#Definimos vectores
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])

In [ ]:
#Concatenamos dos vectores
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Concatenamos más vectores
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Definimos vectores de dos dimensiones
malla = np.array([[1,2,3],[4,5,6]])

In [ ]:
#Concatenamos vectores de dos dimensiones a través del eje 0
np.concatenate([malla,malla])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Concatenamos vectores de dos dimensiones a través del eje 1
np.concatenate([malla,malla], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### np.vstack

Permite apilar verticalmente  arreglos de dimensiones variadas

In [ ]:
#Definimos arreglos de dimensiones variadas
x = np.array([1,2,3])
malla = np.array([[4,5,6],[7,8,9]])

In [ ]:
#concatenamos de forma vertical
np.vstack([x,malla])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### np.hstack
Permite apilar horizontalmente arreglos de dimensiones variadas

In [ ]:
#Definimos arreglos de dimensiones variadas
y = np.array([[0],[0]])
malla = np.array([[4,5,6],[7,8,9]])
print(y)
print(malla)

[[0]
 [0]]
[[4 5 6]
 [7 8 9]]


In [ ]:
#Concatenamos de forma horizontal
np.hstack([y,malla])

array([[0, 4, 5, 6],
       [0, 7, 8, 9]])

# Separar arreglos

Una acción opuesta a concatenar es separar arreglos, de igual manera que con la concatenación, existen varias funciones.

### np.split

Separa un arreglo en múltiples subarreglos

In [ ]:
#Creamos un arreglo que servirá para el ejemplo
np.random.seed(45)
arr = np.random.randint(10,size=10)
print(arr)

[3 0 5 3 4 9 8 1 5 9]


In [ ]:
# Separamos el arreglo en 2 partes iguales
x1,x2 = np.split(arr,2)  #<-- este dos nos dice en cuantos arreglos se separa
print(x1)
print(x2)

[3 0 5 3 4]
[9 8 1 5 9]


In [ ]:
# Si quisieramos separarlo en 3 partes iguales, no sería posible, y nos indicaría un error
x1,x2,x3 = np.split(arr,3)

ValueError: ignored

In [ ]:
#Podemos especificar los índices en los cuales queremos que se haga la separación
x= np.split(arr,[3,7])  #Si tenemos N puntos para separación, tendremos N+1 subarreglos
print(x)
type (x)

[array([3, 0, 5]), array([3, 4, 9, 8]), array([1, 5, 9])]


list

### np.vsplit

Es similar a la anterior, pero se hace una separación vertical

In [ ]:
#Definimos un arreglo que separaremos
mat = np.arange(24).reshape(6,4)
print(mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
#Separamos en dos partes verticales iguales
arriba, abajo = np.vsplit(mat,2)
print(arriba)
print(abajo)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
#Separamos en dos partes verticales de distinto tamaño
arriba,abajo = np.vsplit(mat,[4])
print(arriba)
print(abajo)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]]


In [ ]:
#Separamos en dos partes horizontales
izq, der= np.hsplit(mat,[3])
print(izq)
print(der)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]
 [20 21 22]]
[[ 3]
 [ 7]
 [11]
 [15]
 [19]
 [23]]


In [ ]:
#Obtenemos un error
izq, der= np.hsplit(mat,3)

ValueError: ignored