<a href="https://colab.research.google.com/github/l19060741/Curso-Phyton/blob/main/Anahi_Gonzalez_2_Numpy_Indexaci%C3%B3n_y_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexación y Slicing de arreglos Numpy

Podemos acceder a elementos individuales de los arreglos, y también a grupos de elementos.

## Indexación: Acceder a elementos individuales

In [ ]:
# Cargar las bibliotecas necesarias
import numpy as np

In [ ]:
#Crear un arreglo con 10 enteros aleatorios
np.random.seed(0)
arr = np.random.randint(1,10, 10)

In [ ]:
print(arr)

[6 1 4 4 8 4 6 3 5 8]


Para acceder a los elementos del arreglo, usamos corchetes []

In [ ]:

# Si queremos seleccionar el emeneto con el índice 2, entonces usamos arr[2]
arr[2]

4

In [ ]:
#Para seleccionar el primer elemento
arr[0]

6

Podemos indexar del final del arreglo al inicio usando índices negativos

In [ ]:
arr[-1]

8

In [ ]:
arr[-3]

3

En el caso de arreglos multidimensionales, accedemos a los elementos usando índices en tuplas separadas por coma

In [ ]:
# Construir un arreglo bidimensional aleatorio de forma (3,4) que contenga valores del 0 al 10
np.random.seed(0)
matr = np.random.randint(0,10,size=(3,4))

In [ ]:
print(matr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [ ]:
#Para seleccionar el primer elmento
matr[0,0]

5

In [ ]:
#Para seleccionar otro elemento
matr[1,2]

3

In [ ]:
#Para seleccionar elementos usando índices negativos
matr[-1,0]

2

También es posible modificar valores individuales usando la indexación mostrada. Cabe mencionar que a diferencia de las listas, los arreglos Numpy tienen un tipo fijo, y si quieres insertar un valor flotante en un arreglo e enteros, esto ocasionara que sea truncado (silenciosamente).

In [ ]:
matr[0,1]=11

In [ ]:
print(matr)

[[ 5 11  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [ ]:
matr[1,3] = 3.1416
print(matr)

[[ 5 11  3  3]
 [ 7  9  3  3]
 [ 2  4  7  6]]


# Slicing: Accediendo a subarreglos

Para acceder a subarreglos utilizamos una notación especial que hace uso del caracter 'dos puntos' (:). Para obtener el subarreglo (rebanada o slice en inglés) se utiliza lo siguiente:

arr[inicio:final:paso]

En dado caso que no se especifiquen, los valores por default son:

- inicio=0
- final=tamaño de la dimensión
- paso=1

### Arreglos unidimensionales

In [ ]:
#Otra forma de hacerlo
arr[1:-1]

array([1, 4, 4, 8, 4, 6, 3, 5])

In [ ]:
#Obtener los primeros 4 elementos
arr[:5]

array([6, 1, 4, 4, 8])

In [ ]:
#Seleccionar los elementos después del índice 5
arr[5:]

array([4, 6, 3, 5, 8])

In [ ]:
#Seleccionar desde el índice 1 hasta el final, tomando valores de dos en dos
arr[1::2]

array([1, 4, 4, 3, 8])

Los pasos también pueden ser negativos, y cuando esto sucede, el inicio y final son intercambiados.

In [ ]:
# Seleccionar desde el segundo elemento hasta el penúltimo para conseguir este subarreglo [8 6 1 4 4 4 8 2]
arr[1:9]

array([1, 4, 4, 8, 4, 6, 3, 5])

In [ ]:
#Imprimir nuevamente el arreglo
print(arr)

[6 1 4 4 8 4 6 3 5 8]


In [ ]:
# Construir un arreglo unidimensional aleatorio que contenga 10 valores del 1 al 9
np.random.seed(0)
arr = np.random.randint(1,9,10)
print(arr)


[5 8 6 1 4 4 4 8 2 4]


In [ ]:
#Seleccionar desde el penúltimo elemento hasta el 3er elemento 
arr[-2:1:-1]

array([2, 8, 4, 4, 4, 1, 6])

In [ ]:
#Invertir todos los elementos
arr[::-1]

array([4, 2, 8, 4, 4, 4, 1, 6, 8, 5])

### Arreglos bidimensionales

In [ ]:
# Construir un arreglo bidimensional aleatorio de forma (4,3) que contenga valores del 1 al 9
np.random.seed(0)
matr = np.random.randint(1,9,size=(4,3))
print(matr)

[[5 8 6]
 [1 4 4]
 [4 8 2]
 [4 6 3]]


In [ ]:
#Seleccionar la submatriz formada por las dos primeras filas y las dos primeras columnas
matr[:2,:2]

array([[5, 8],
       [1, 4]])

In [ ]:
#Selecciona la submatriz formada por las tres ultimas filas y las dos primeras columnas
matr[1:,:2]

array([[1, 4],
       [4, 8],
       [4, 6]])

In [ ]:
#Seleccionar la submatriz que tiene los valores de los renglones de dos en dos y todas las comunas
matr[::2,:]

array([[5, 8, 6],
       [4, 8, 2]])

In [ ]:
#Seleccionar el 3 renglón
matr[2,:]

array([4, 8, 2])

In [ ]:
#Seleccionar la 1ra columna
matr[:,0]

array([5, 1, 4, 4])

In [ ]:
#Para el caso de la selección de renglones, se puede usar esta notación mas compacta
matr[2]

array([4, 8, 2])

In [ ]:
#Para el caso de la selección de elemento
matr[2][1]

8

# Copias de arreglos
Algo **importante** es el hecho de que las rebanadas regresan vistas y no copias de los arreglos. 

In [ ]:
# Imprimir nuevamente la matriz
print(matr)

[[5 8 6]
 [1 4 4]
 [4 8 2]
 [4 6 3]]


In [ ]:
#Seleccionar la submatriz formada por los últimos rengloes y las últimas dos columnas
sub_matr=matr[2:,1:]
print(sub_matr)

[[8 2]
 [6 3]]


In [ ]:
#Modificar la submatriz
sub_matr[0,0] = 0

In [ ]:
#Observar nuevamente el valor de la matriz original y ver que sucede
print(matr)

[[5 8 6]
 [1 4 4]
 [4 0 2]
 [4 6 3]]


In [ ]:
sub_matr_copy=matr[2:,1:].copy()
print(sub_matr)

[[0 2]
 [6 3]]


In [ ]:
sub_matr_copy[0,0] = 15

In [ ]:
print(matr)

[[5 8 6]
 [1 4 4]
 [4 0 2]
 [4 6 3]]


In [ ]:
import numpy as np
import copy
array = np.array([1,2,3,4])
array2 = array.copy()
array[0] = array[0] + 1
print(array)
print(array2)


[2 2 3 4]
[1 2 3 4]
